### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by irisxu02**

### CODE REVIEW

**Review by irisxu02 — COMMENTED** [review]
[1fb5adf](https://github.com/irisxu02/google-sps22/pull/10/commits/1fb5adfb8628736fe25dc51fc0d016ac3ecda53f) commit message should be "Make variable name consistent with elementId, remove unused function"

**Comment by irisxu02** [comment]
I want everything to go to the main branch. If I merge this do changes go to main or main-content?

**Comment by kuanyiwu** [comment]
@irisxu02  The changes will apply to main-content. Do you have any changes in main-content? If you want an up-to-date branch you can do `git pull` on main and then create a new branch.

**Comment by irisxu02** [comment]
I don't have changes in main-content. Ready to merge.

**Comment by kuanyiwu** [comment]
Yeah, feel free to go ahead and merge. Or delete main-content and create a new branch, up to you.

**Pull request merged**
